### ISSUE TITLE
I get the button to choose to force clone, but it doesn't do anything.

### ISSUE THREAD

**Issue by Zayoe4** [matix2/ForceClone#1]
![image](https://user-images.githubusercontent.com/10657721/116941011-e088a980-ac3c-11eb-88e7-3e1232ba3144.png)
I can click on the button, but my character doesn't change.

**Comment by matix2** [comment]
That button could be buggy sometimes, try clicking on the bottom edge of the button and see if that works

**Comment by Zayoe4** [comment]
You're right, it worked.
