### ISSUE TITLE
error

### ISSUE THREAD

**Issue by quazi00** [matix2/ForceClone#15]
I loaded it up in the newest version of melon loader and gave me this error

Exception in coroutine of type ForceClone.Main+<UiManagerInitializer>d__1, ForceClone, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: System.MissingMethodException: VRCUiManager VRCUiManager.Method_Internal_Static_get_VRCUiManager_0()
  at MelonLoader.Support.Coroutines.ProcessNextOfCoroutine (System.Collections.IEnumerator enumerator) [0x0000d] in <42608154b4be43d399be6120b3678d66>:0

**Comment by pp0236** [comment]
not working with open-beta client
