### ISSUE TITLE
Button does not show up

### ISSUE THREAD

**Issue by ThatAnimeBoii** [matix2/ForceClone#2]
Maybe I'm stupid or didn't read something, but I have the latest melonloader and the latest version of the mod in my mod folder in vrchat. Whenever I laser someone nothing pops up, and the console tells me that the mod is loaded. I don't see any options in mod settings either, but I don't know if I am supposed to.

**Comment by matix2** [comment]
Make sure you're using melonloader 0.3.0
![20210620081807_1](https://user-images.githubusercontent.com/40892703/122673786-19a2bc00-d1a0-11eb-8955-f0696a5e0958.jpg)
