### ISSUE TITLE
Broken on latest VRChat builds

### ISSUE THREAD

**Issue by Lexian-droid** [matix2/ForceClone#20]
Hello, This dll is broken on the most recent builds of VRChat, it only displays "Auto Hook" and nothing else alongside it.
There are no options to force clone anyone in the game.
I downloaded MelonLoader as well, but it didn't make any difference, just says "Auto hook"

**Comment by matix2** [comment]
There is not anymore a button to force clone the avatars, you can just now clone them as you normally would, if you prefer the old method please use version 1.0.9.
