### ISSUE TITLE
i dont understand the build requirements... help?

### ISSUE THREAD

**Issue by pitolyn** [matix2/ForceClone#4]
sorry im not too sure what required libraries you are talking about... or which Dependencies folder you are talking about (the melonloader Dependencies folder or the main vrchat one?)
i cant seem to get the mod to work T-T so i figure im doing something wrong, if someone can help i would greatly appreciate it.

**Comment by matix2** [comment]
You only need the dependencies if you want to build the mod by yourself, otherwise just put [this](https://github.com/matix2/ForceClone/releases/download/1.0.2/ForceClone.dll) .dll file inside your Mods folder
